name: golang-ci-test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19"
        id: go
      - name: check out
        uses: actions/checkout@v3

      # 処理を高速化するために環境をキャッシュ
      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: go test ./... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v0
